import {
  Trophy,
  Award,
  Crown,
  Medal,
  Flame,
  Star,
  Sparkles,
  Gamepad2,
  Joystick,
  Compass,
  Map,
  TrendingUp,
  Users,
  HeartHandshake,
  CalendarCheck,
  CalendarHeart,
  Coins,
  Gem,
  ShoppingBag,
  Worm,
  LayoutGrid,
  Grid2x2,
  Crosshair,
  Zap,
  Moon,
  Sun,
  Brain,
  Rocket,
  PartyPopper,
  Binary,
  Save,
  Tv,
  Target,
  HelpCircle,
  type LucideIcon,
} from "lucide-react";

const MAP: Record<string, LucideIcon> = {
  trophy: Trophy,
  award: Award,
  crown: Crown,
  medal: Medal,
  flame: Flame,
  star: Star,
  sparkles: Sparkles,
  "gamepad-2": Gamepad2,
  joystick: Joystick,
  compass: Compass,
  map: Map,
  "trending-up": TrendingUp,
  users: Users,
  "heart-handshake": HeartHandshake,
  "calendar-check": CalendarCheck,
  "calendar-heart": CalendarHeart,
  coins: Coins,
  gem: Gem,
  "shopping-bag": ShoppingBag,
  worm: Worm,
  "layout-grid": LayoutGrid,
  "grid-2x2": Grid2x2,
  crosshair: Crosshair,
  zap: Zap,
  moon: Moon,
  sun: Sun,
  brain: Brain,
  rocket: Rocket,
  "party-popper": PartyPopper,
  binary: Binary,
  save: Save,
  tv: Tv,
  target: Target,
};

/** Render a Lucide icon by its kebab-case name (from DB icon fields). */
export function DynamicIcon({ name, className }: { name: string; className?: string }) {
  const Icon = MAP[name] ?? HelpCircle;
  return <Icon className={className} />;
}
